package com.example.kilt.models.config

data class PropMapping(
    val designation: Designation,
    val where_located: Located,
    val line_of_houses: HouseLineList,
    val property_type: PropertyType,
    val furniture: Furniture,
    val num_rooms: NumRooms,
    val construction_type: ConstructionTypes,
    val floor:Floor,
    val furniture_list: FurnitureList,
    val new_conveniences: ListOfConveniences,
    val rent_period:RentPeriod,
    val bathroom:Bathroom,
    val new_balcony:NewBalcony,
    val bathroom_inside: BathroomInside,
    val security: Security,
    val balcony: Balcony,
    val toilet_separation:ToiletSeparation,
    val loggia: Loggia,
    val windows: Windows,
    val suits_for:SuitsFor,
    val is_bailed: IsBailed,
    val former_dormitory: FormerDormitory,
    val internet: Internet,
    val balcony_glass:BalconyGlass,
    val door: Door,
    val parking:Parking,
    val floor_material:FloorMaterial,
    val condition: ConditionList,
    val heating: HeatingList,
    val sewer: SewerList,
    val drinking_water: DrinkingWaterList,
    val irrigation_water: IrrigationWaterList,
    val electricity: ElectricityList,
    val telephone: TelephoneList,
    val active_business : ActiveBusinessList,
    val has_renters: HasRentersList,
    val free_planning: FreePlanningList,
    val business_condition : BusinessConditionList,
    val business_parking: BusinessParkingList,
    val business_entrance: BusinessEntranceList,
    val communications : CommunicationsList
)