package com.example.kilt.core.navigation

enum class NavPath {
    HOME,SEARCH,FAVORITES,PROFILE,

    BLOGPAGE,NEWS,HOMEDETAILS,CHOOSECITYPAGE,

    LOGIN,ENTERFOURCODEPAGE,REGISTRATIONPAGE,OWNERPAGE,AGENCYPAGE,ENTERSIXCODEPAGE,EDITPROFILE,NOTIFICATIONSSCREEN,USERPROFILESCREEN,

    CHOOSECITYINEDIT,



    ADDNEWLISTINGSCREEN,MYANNOUNCEMENTSCREEN,IDENTIFICATIONSCREEN
}