package com.example.kilt.models

import com.example.kilt.models.config.Image

data class PropertyItem(
    val id: Int,
    val deal_type: Int,
    val listing_type: Int,
    val property_type: Int,
    val num_rooms: Int,
    val area: Double,
    val floor: Int,
    val num_floors: Int?,
    val rent_period: Int,
    val living_area:Int,
    val price: String,
    val built_year:Int,
    val address_string: String,
    val description: String? = null,
    val seller_whatsapp: String,
    val seller_phone_number: String,
    val user_type: Int,
    val status: Int,
    val first_image: String,
    val first_image_cloud: Int,
    val lat: Double,
    val lng: Double,
    val type: String,
    val images: List<Image>,
    val designation: String,
    val where_located: Int,
    val line_of_houses: Int,
    val ceiling_height: Double,
    val furniture: Int,
    val max_usage: String,
)