package com.example.kilt.navigation

enum class NavPath {
    HOME,SEARCH,FAVORITES,PROFILE,

    BLOGPAGE,NEWS,HOMEDETAILS,CHOOSECITYPAGE,

    LOGIN,ENTERFOURCODEPAGE,REGISTRATIONPAGE,OWNERPAGE,AGENCYPAGE,AUTHENTICATEDPROFILESCREEN,ENTERSIXCODEPAGE
}